### ISSUE TITLE
Building instructions would be welcome

### ISSUE THREAD

**Issue by rulatir** [robpvn/MonoDevelopGtkSharp3Template#4]
Obviously simply opening the solution in MonoDevelop is not the right path towards the goal of building this extension. Monodevelop fails to open it:

```
„/path-to-project/MonoDevelop.GTKSharp3Project/MonoDevelop.GTKSharp3Project.csproj”: The type initializer for 'MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext' threw an exception.
```
So how do I build it? Trying to get into the whole C#-on-linux thing after an 8 year break.

**Comment by robpvn** [comment]
Goodness, I haven't looked at this in at least seven years - It certainly was supposed to be built by opening it in MonoDevelop, but I imagine that so many things have changed in MonoDevelop since then that it no longer can be opened and built properly.  On top of that, the template must be very outdated in itself, so I don't think you should spend too much time trying to make this work. 🤷‍♂️

**Comment by rulatir** [comment]
Ouch. I didn't do what I usually do, namely glance at the timestamps column on the repository homepage.
